[package]
name = "spade-marlin-macro"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
spade-lang.workspace = true
spade-types.workspace = true
spade-hir.workspace = true
spade-hir-lowering.workspace = true
spade-common.workspace = true

bincode.workspace = true
camino.workspace = true
itertools.workspace = true
marlin-verilator.workspace = true
marlin-verilog-macro-builder.workspace = true
num.workspace = true
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = "2.0.111"
