[build-system]
requires = ["maturin>=0.14,<0.15"]
build-backend = "maturin"

[project]
name = "spade"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Development Status :: 3 - Alpha",
    "Topic :: Scientific/Engineering :: Electronic Design Automation (EDA)"
]
dependencies = ["cocotb~=1.7.2", "ansicolors>=1.1.8"]
