[package]
name = "spade-mir-lowering"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
spade-mir.workspace = true
spade-lir.workspace = true
spade-common.workspace = true
spade-diagnostics.workspace = true

num.workspace = true
