[package]
name = "spade-parser"
version.workspace = true
authors = ["TheZoq2 <frans.skarman@protonmail.com>"]
edition.workspace = true
license.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
spade-codespan.workspace = true
colored.workspace = true
local-impl.workspace = true
logos.workspace = true
tracing.workspace = true
num.workspace = true
itertools.workspace = true

spade-ast = {path = "../spade-ast"}
spade-common = {path = "../spade-common"}
spade-diagnostics = {path = "../spade-diagnostics"}
spade-macros = {path = "../spade-macros"}
